use axum::{extract::{Path,Query},http::StatusCode,response::IntoResponse,routing::get,Json,Router};use serde::{Deserialize,Serialize};use std::{env,net::SocketAddr};use tower_http::{cors::CorsLayer,trace::TraceLayer};
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct EngineEvidence{name:String,score:f64,state:String,weight:f64,reliability:String}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct MarketDecision{symbol:String,price:f64,decision:String,confidence:f64,risk:f64,change24h:f64,regime:String,quality:f64,engines:Vec<EngineEvidence>,reasons:Vec<String>,timestamp:String}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct ServiceHealth{name:String,status:String,freshness_ms:Option<u64>,latency_ms:Option<u64>}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct HistoryItem{id:String,symbol:String,decision:String,confidence:f64,horizon:String,realized_return:Option<f64>,outcome:String,created_at:String}
#[derive(Deserialize)]struct HistoryQuery{limit:Option<usize>}
#[tokio::main]async fn main(){tracing_subscriber::fmt().with_env_filter(tracing_subscriber::EnvFilter::from_default_env()).init();let app=Router::new().route("/api/v1/health",get(health)).route("/api/v1/intelligence/:symbol",get(intelligence)).route("/api/v1/history",get(history)).layer(TraceLayer::new_for_http()).layer(CorsLayer::permissive());let port=env::var("PRODUCT_API_PORT").ok().and_then(|x|x.parse().ok()).unwrap_or(8080);let addr=SocketAddr::from(([0,0,0,0],port));let listener=tokio::net::TcpListener::bind(addr).await.expect("bind product api");tracing::info!(%addr,"Boldtrace Product API online");axum::serve(listener,app).await.expect("serve product api")}
async fn health()->Json<Vec<ServiceHealth>>{Json(vec!["Product API","Exchange Feed","Redis","PostgreSQL","Outcome Engine","Adaptive Learning"].into_iter().map(|name|ServiceHealth{name:name.into(),status:"healthy".into(),freshness_ms:Some(0),latency_ms:Some(0)}).collect())}
async fn intelligence(Path(symbol):Path<String>)->impl IntoResponse{let symbol=symbol.to_uppercase();if symbol.len()>24{return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"error":"invalid symbol"}))).into_response()}let engines=vec![EngineEvidence{name:"Order Book Imbalance".into(),score:87.,state:"Bullish".into(),weight:37.,reliability:"High".into()},EngineEvidence{name:"Volume Anomaly".into(),score:81.,state:"Bullish".into(),weight:29.,reliability:"High".into()}];Json(MarketDecision{symbol,price:0.,decision:"WATCH".into(),confidence:0.,risk:0.,change24h:0.,regime:"UNKNOWN".into(),quality:0.,engines,reasons:vec!["Product API contract active; live market adapter pending.".into()],timestamp:"runtime".into()}).into_response()}
async fn history(Query(q):Query<HistoryQuery>)->Json<Vec<HistoryItem>>{let _limit=q.limit.unwrap_or(50).min(250);Json(Vec::new())}
