mod adapter;mod live_store;use adapter::from_score;use axum::{extract::{Path,Query,State},http::StatusCode,response::IntoResponse,routing::get,Json,Router};use live_store::LiveStore;use serde::{Deserialize,Serialize};use std::{env,net::SocketAddr};use tower_http::{cors::CorsLayer,trace::TraceLayer};
#[derive(Clone)]struct AppState{live:Option<LiveStore>}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct EngineEvidence{name:String,score:f64,state:String,weight:f64,reliability:String}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct MarketDecision{symbol:String,price:f64,decision:String,confidence:f64,risk:f64,change24h:f64,regime:String,quality:f64,engines:Vec<EngineEvidence>,reasons:Vec<String>,timestamp:String}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct ServiceHealth{name:String,status:String,freshness_ms:Option<u64>,latency_ms:Option<u64>}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct HistoryItem{id:String,symbol:String,decision:String,confidence:f64,horizon:String,realized_return:Option<f64>,outcome:String,created_at:String}
#[derive(Deserialize)]struct HistoryQuery{limit:Option<usize>}
#[tokio::main]async fn main(){tracing_subscriber::fmt().with_env_filter(tracing_subscriber::EnvFilter::from_default_env()).init();let live=env::var("REDIS_URL").ok().and_then(|u|LiveStore::new(&u).ok());let state=AppState{live};let app=Router::new().route("/api/v1/health",get(health)).route("/api/v1/intelligence/:symbol",get(intelligence)).route("/api/v1/history",get(history)).with_state(state).layer(TraceLayer::new_for_http()).layer(CorsLayer::permissive());let port=env::var("PRODUCT_API_PORT").ok().and_then(|x|x.parse().ok()).unwrap_or(8080);let addr=SocketAddr::from(([0,0,0,0],port));let listener=tokio::net::TcpListener::bind(addr).await.expect("bind product api");tracing::info!(%addr,"Boldtrace Product API online");axum::serve(listener,app).await.expect("serve product api")}
async fn health(State(s):State<AppState>)->Json<Vec<ServiceHealth>>{let redis_ok=match s.live.as_ref(){Some(x)=>x.ping().await,None=>false};Json(vec![ServiceHealth{name:"Product API".into(),status:"healthy".into(),freshness_ms:Some(0),latency_ms:Some(0)},ServiceHealth{name:"Redis".into(),status:if redis_ok{"healthy"}else{"degraded"}.into(),freshness_ms:None,latency_ms:None}])}
async fn intelligence(State(s):State<AppState>,Path(symbol):Path<String>)->impl IntoResponse{let symbol=symbol.to_uppercase();if symbol.len()>24||!symbol.chars().all(|c|c.is_ascii_alphanumeric()||c=='_'||c=='-'){return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"error":"invalid symbol"}))).into_response()}let Some(store)=s.live.as_ref()else{return(StatusCode::SERVICE_UNAVAILABLE,Json(serde_json::json!({"error":"live score store unavailable"}))).into_response()};let score=match store.score(&symbol).await{Ok(Some(x))=>x,Ok(None)=>return(StatusCode::NOT_FOUND,Json(serde_json::json!({"error":"no live score for symbol"}))).into_response(),Err(e)=>{tracing::warn!(error=%e,%symbol,"live score read failed");return(StatusCode::SERVICE_UNAVAILABLE,Json(serde_json::json!({"error":"live score read failed"}))).into_response()}};let d=from_score(&score,100.,0.);let engines=vec![EngineEvidence{name:"Order Book Imbalance".into(),score:score.order_book_imbalance,state:state_label(score.order_book_imbalance),weight:0.,reliability:"Pending".into()},EngineEvidence{name:"Volume Anomaly".into(),score:score.volume_anomaly,state:state_label(score.volume_anomaly),weight:0.,reliability:"Pending".into()},EngineEvidence{name:"Funding Extreme".into(),score:score.funding_extreme,state:state_label(score.funding_extreme),weight:0.,reliability:"Pending".into()},EngineEvidence{name:"RSI Divergence".into(),score:score.rsi_divergence,state:state_label(score.rsi_divergence),weight:0.,reliability:"Pending".into()}];Json(MarketDecision{symbol:score.symbol,price:0.,decision:d.decision,confidence:d.confidence,risk:d.risk,change24h:0.,regime:"UNKNOWN".into(),quality:d.quality,engines,reasons:d.reasons,timestamp:score.timestamp.to_string()}).into_response()}
fn state_label(v:f64)->String{if v>=70.{"High"}else if v>=50.{"Moderate"}else{"Low"}.into()}
async fn history(Query(q):Query<HistoryQuery>)->Json<Vec<HistoryItem>>{let _limit=q.limit.unwrap_or(50).min(250);Json(Vec::new())}
