//! Edge-triggered score alarms plus smart decision alerts.
use std::{collections::{HashMap,HashSet},sync::Mutex};use score_engine::{Decision,MetaDecision};
struct Alarm{telegram_id:i64,symbol:String,threshold:f64,was_above:bool}
#[derive(Default)]pub struct AlarmRegistry{alarms:Mutex<Vec<Alarm>>}
impl AlarmRegistry{pub fn set(&self,telegram_id:i64,symbol:&str,threshold:f64){let mut a=self.alarms.lock().expect("alarm registry lock poisoned");a.retain(|x|!(x.telegram_id==telegram_id&&x.symbol==symbol));a.push(Alarm{telegram_id,symbol:symbol.to_string(),threshold,was_above:false});}pub fn crossed(&self,symbol:&str,score:f64)->Vec<(i64,f64)>{let mut a=self.alarms.lock().expect("alarm registry lock poisoned");let mut t=vec![];for x in a.iter_mut().filter(|x|x.symbol==symbol){let above=score>=x.threshold;if above&&!x.was_above{t.push((x.telegram_id,x.threshold));}x.was_above=above;}t}pub fn subscribers(&self,symbol:&str)->Vec<i64>{let a=self.alarms.lock().expect("alarm registry lock poisoned");let mut ids:HashSet<i64>=a.iter().filter(|x|x.symbol==symbol).map(|x|x.telegram_id).collect();let mut out:Vec<i64>=ids.drain().collect();out.sort_unstable();out}}
#[derive(Debug,Clone,Copy,PartialEq)]pub struct AlertPolicy{pub min_confidence:f64,pub max_risk:f64,pub cooldown_ms:i64}
impl Default for AlertPolicy{fn default()->Self{Self{min_confidence:60.0,max_risk:80.0,cooldown_ms:15*60*1000}}}
impl AlertPolicy{pub fn adaptive(samples:usize,avg_risk:f64,avg_data_quality:f64,avg_agreement:f64)->Self{if samples<30{return Self::default();}let reliability=(avg_data_quality*0.5+avg_agreement*0.5).clamp(0.0,100.0);let min_confidence=(70.0-(reliability-50.0)*0.10).clamp(62.0,75.0);let max_risk=(75.0-(avg_risk-50.0)*0.10).clamp(65.0,80.0);let cooldown_ms=if reliability<45.0{30*60*1000}else if reliability<65.0{20*60*1000}else{15*60*1000};Self{min_confidence,max_risk,cooldown_ms}}}
#[derive(Debug,Clone,PartialEq)]pub struct SmartAlert{pub symbol:String,pub decision:Decision,pub confidence:f64,pub risk:f64}
#[derive(Default)]pub struct SmartAlertGate{last:Mutex<HashMap<String,(Decision,i64)>>}
impl SmartAlertGate{pub fn evaluate_with_policy(&self,symbol:&str,d:&MetaDecision,now_ms:i64,policy:AlertPolicy)->Option<SmartAlert>{if matches!(d.decision,Decision::Neutral|Decision::NoTrade)||d.confidence<policy.min_confidence||d.risk>=policy.max_risk{return None;}let mut last=self.last.lock().expect("smart alert lock poisoned");if let Some((previous,at))=last.get(symbol){if *previous==d.decision&&now_ms-*at<policy.cooldown_ms{return None;}}last.insert(symbol.to_string(),(d.decision,now_ms));Some(SmartAlert{symbol:symbol.to_string(),decision:d.decision,confidence:d.confidence,risk:d.risk})}}
#[cfg(test)]mod tests{use super::*;#[test]fn triggers_once_on_upward_crossing(){let r=AlarmRegistry::default();r.set(1,"BTCUSDT",70.0);assert_eq!(r.crossed("BTCUSDT",75.0),vec![(1,70.0)]);assert!(r.crossed("BTCUSDT",80.0).is_empty());}#[test]fn lists_unique_subscribers(){let r=AlarmRegistry::default();r.set(2,"BTCUSDT",70.0);r.set(1,"BTCUSDT",80.0);assert_eq!(r.subscribers("BTCUSDT"),vec![1,2]);}#[test]fn smart_alert_respects_cooldown(){let g=SmartAlertGate::default();let d=MetaDecision{decision:Decision::Long,signal_quality:80.0,confidence:75.0,risk:20.0};let policy=AlertPolicy{cooldown_ms:60000,..AlertPolicy::default()};assert!(g.evaluate_with_policy("BTCUSDT",&d,1000,policy).is_some());assert!(g.evaluate_with_policy("BTCUSDT",&d,2000,policy).is_none());}#[test]fn risky_signal_is_blocked(){let g=SmartAlertGate::default();let d=MetaDecision{decision:Decision::StrongLong,signal_quality:90.0,confidence:90.0,risk:90.0};let policy=AlertPolicy{cooldown_ms:60000,..AlertPolicy::default()};assert!(g.evaluate_with_policy("BTCUSDT",&d,1000,policy).is_none());}#[test]fn weak_history_tightens_policy(){let p=AlertPolicy::adaptive(200,75.0,30.0,35.0);assert!(p.min_confidence>60.0);assert!(p.max_risk<80.0);assert!(p.cooldown_ms>15*60*1000);}#[test]fn insufficient_history_keeps_defaults(){assert_eq!(AlertPolicy::adaptive(10,90.0,10.0,10.0),AlertPolicy::default());}}
