use score_engine::IntelligenceSnapshot;use serde_json::{json,Value};use sqlx::{FromRow,PgPool};use crate::outcome_engine::Outcome;
#[derive(Debug,Clone,FromRow)]pub struct LedgerRecord{pub symbol:String,pub score:f64,pub decision:String,pub rationale:String,pub confidence:f64,pub decided_at_millis:i64,pub metadata:Value}
#[derive(Debug,Clone,PartialEq)]pub struct DecisionPerformance{pub samples:usize,pub avg_score:f64,pub avg_confidence:f64,pub avg_risk:f64,pub avg_data_quality:f64,pub avg_agreement:f64}
#[derive(Debug,Clone,PartialEq)]pub struct OutcomePerformance{pub samples:usize,pub win_rate:f64,pub avg_directional_return_pct:f64}
#[derive(Clone)]pub struct DecisionLedger{pool:PgPool}
impl DecisionLedger{pub fn new(pool:PgPool)->Self{Self{pool}}pub async fn append(&self,s:&IntelligenceSnapshot)->Result<(),sqlx::Error>{let rationale=if s.explanation.reasons.is_empty(){s.explanation.headline.clone()}else{s.explanation.reasons.join("; ")};let metadata=json!({"signal_quality":s.decision.signal_quality,"risk":s.decision.risk,"data_quality":s.data_quality,"agreement":s.agreement,"derivatives_score":s.derivatives_score,"warnings":s.explanation.warnings,"headline":s.explanation.headline,"engine":"boldtrace-intelligence-v2"});sqlx::query("INSERT INTO decision_ledger (symbol,score,decision,rationale,confidence,decided_at_millis,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7)").bind(&s.symbol).bind(s.score).bind(format!("{:?}",s.decision.decision)).bind(rationale).bind(s.decision.confidence).bind(s.timestamp).bind(metadata).execute(&self.pool).await?;Ok(())}
pub async fn append_outcome(&self,o:&Outcome)->Result<(),sqlx::Error>{sqlx::query("INSERT INTO decision_outcomes(symbol,decision,decided_at_millis,horizon_minutes,entry_price,exit_price,return_pct,directional_return_pct,correct,evaluated_at_millis) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(symbol,decided_at_millis,horizon_minutes) DO NOTHING").bind(&o.symbol).bind(&o.decision).bind(o.decided_at_millis).bind(o.horizon_minutes).bind(o.entry_price).bind(o.exit_price).bind(o.return_pct).bind(o.directional_return_pct).bind(o.correct).bind(o.evaluated_at_millis).execute(&self.pool).await?;Ok(())}
pub async fn outcome_performance(&self,symbol:&str,horizon_minutes:i32,limit:i64)->Result<Option<OutcomePerformance>,sqlx::Error>{let rows:(i64,Option<f64>,Option<f64>)=sqlx::query_as("SELECT COUNT(*)::BIGINT,AVG(CASE WHEN correct THEN 1.0 ELSE 0.0 END)::DOUBLE PRECISION,AVG(directional_return_pct)::DOUBLE PRECISION FROM (SELECT correct,directional_return_pct FROM decision_outcomes WHERE symbol=$1 AND horizon_minutes=$2 ORDER BY evaluated_at_millis DESC LIMIT $3) x").bind(symbol).bind(horizon_minutes).bind(limit.clamp(1,5000)).fetch_one(&self.pool).await?;if rows.0==0{return Ok(None);}Ok(Some(OutcomePerformance{samples:rows.0 as usize,win_rate:rows.1.unwrap_or(0.0)*100.0,avg_directional_return_pct:rows.2.unwrap_or(0.0)}))}
pub async fn replay(&self,symbol:&str,limit:i64)->Result<Vec<LedgerRecord>,sqlx::Error>{sqlx::query_as::<_,LedgerRecord>("SELECT symbol,score,decision,rationale,confidence,decided_at_millis,metadata FROM decision_ledger WHERE symbol=$1 ORDER BY decided_at_millis DESC LIMIT $2").bind(symbol).bind(limit.clamp(1,1000)).fetch_all(&self.pool).await}
pub async fn performance(&self,symbol:&str,limit:i64)->Result<Option<DecisionPerformance>,sqlx::Error>{let rows=self.replay(symbol,limit).await?;if rows.is_empty(){return Ok(None);}let n=rows.len() as f64;let mut score=0.0;let mut confidence=0.0;let mut risk=0.0;let mut quality=0.0;let mut agreement=0.0;for r in &rows{score+=r.score;confidence+=r.confidence;risk+=r.metadata.get("risk").and_then(Value::as_f64).unwrap_or(0.0);quality+=r.metadata.get("data_quality").and_then(Value::as_f64).unwrap_or(0.0);agreement+=r.metadata.get("agreement").and_then(Value::as_f64).unwrap_or(0.0);}Ok(Some(DecisionPerformance{samples:rows.len(),avg_score:score/n,avg_confidence:confidence/n,avg_risk:risk/n,avg_data_quality:quality/n,avg_agreement:agreement/n}))}}
