//! Evaluates directional decisions against future prices at fixed horizons.
use std::collections::VecDeque;use std::sync::Mutex;use score_engine::Decision;
pub const HORIZONS:[i32;3]=[15,60,240];
#[derive(Debug,Clone,PartialEq)]pub struct PendingOutcome{pub symbol:String,pub decision:Decision,pub decided_at_millis:i64,pub entry_price:f64,pub completed:[bool;3]}
#[derive(Debug,Clone,PartialEq)]pub struct Outcome{pub symbol:String,pub decision:String,pub decided_at_millis:i64,pub horizon_minutes:i32,pub entry_price:f64,pub exit_price:f64,pub return_pct:f64,pub directional_return_pct:f64,pub correct:bool,pub evaluated_at_millis:i64}
#[derive(Default)]pub struct OutcomeTracker{pending:Mutex<VecDeque<PendingOutcome>>}
impl OutcomeTracker{pub fn register(&self,symbol:&str,decision:Decision,decided_at_millis:i64,entry_price:f64){if entry_price<=0.0||matches!(decision,Decision::Neutral|Decision::NoTrade){return;}let mut p=self.pending.lock().expect("outcome tracker lock poisoned");if p.back().is_some_and(|x|x.symbol==symbol&&x.decision==decision&&decided_at_millis-x.decided_at_millis<60_000){return;}p.push_back(PendingOutcome{symbol:symbol.to_string(),decision,decided_at_millis,entry_price,completed:[false;3]});while p.len()>10_000{p.pop_front();}}
pub fn evaluate_price(&self,symbol:&str,price:f64,at_millis:i64)->Vec<Outcome>{let mut p=self.pending.lock().expect("outcome tracker lock poisoned");let mut out=Vec::new();for item in p.iter_mut().filter(|x|x.symbol==symbol){for(i,h)in HORIZONS.iter().enumerate(){if !item.completed[i]&&at_millis-item.decided_at_millis>=i64::from(*h)*60_000{if let Some(o)=evaluate(item,price,*h,at_millis){out.push(o);}item.completed[i]=true;}}}p.retain(|x|!x.completed.iter().all(|v|*v));out}}
pub fn evaluate(p:&PendingOutcome,exit_price:f64,horizon_minutes:i32,evaluated_at_millis:i64)->Option<Outcome>{if p.entry_price<=0.0||exit_price<=0.0{return None;}let direction=match p.decision{Decision::StrongLong|Decision::Long=>1.0,Decision::StrongShort|Decision::Short=>-1.0,_=>return None};let return_pct=(exit_price/p.entry_price-1.0)*100.0;let directional_return_pct=return_pct*direction;Some(Outcome{symbol:p.symbol.clone(),decision:format!("{:?}",p.decision),decided_at_millis:p.decided_at_millis,horizon_minutes,entry_price:p.entry_price,exit_price,return_pct,directional_return_pct,correct:directional_return_pct>0.0,evaluated_at_millis})}
#[cfg(test)]mod tests{use super::*;fn pending(d:Decision)->PendingOutcome{PendingOutcome{symbol:"BTCUSDT".into(),decision:d,decided_at_millis:0,entry_price:100.0,completed:[false;3]}}#[test]fn long_profit_is_correct(){let o=evaluate(&pending(Decision::Long),105.0,60,3_600_000).unwrap();assert!(o.correct);assert!(o.directional_return_pct>0.0);}#[test]fn short_profit_is_correct(){assert!(evaluate(&pending(Decision::Short),95.0,60,3_600_000).unwrap().correct);}#[test]fn tracker_closes_each_horizon_once(){let t=OutcomeTracker::default();t.register("BTCUSDT",Decision::Long,0,100.0);assert_eq!(t.evaluate_price("BTCUSDT",101.0,900_000).len(),1);assert!(t.evaluate_price("BTCUSDT",101.0,900_001).is_empty());assert_eq!(t.evaluate_price("BTCUSDT",102.0,3_600_000).len(),1);assert_eq!(t.evaluate_price("BTCUSDT",103.0,14_400_000).len(),1);}}
