import{useIntelligence}from'../api/useIntelligence';import{useI18n}from'../i18n';import type{Copy}from'../i18n';
export function EngineMatrix(){
  const{data,loading,error,refresh}=useIntelligence('BTCUSDT');
  const{t}=useI18n();
  if(loading&&!data)return <State t={t} text={t.emLoading}/>;
  if(!data)return <State t={t} text={t.emUnavailable} detail={error||undefined} retry={refresh}/>;
  return <div className="page"><div className="page-head"><div><span className="eyebrow">{t.emEyebrow}</span><h1>{t.emTitle}</h1><p>{t.emSubPrefix} {data.symbol}.</p></div><button className="system-pill" onClick={refresh}><i/>{error?t.statusDegraded:`${data.engines.length} ${t.emEnginesLive}`}</button></div><section className="panel"><div className="engine-table"><div className="engine-row engine-head"><span>{t.emColEngine}</span><span>{t.emColScore}</span><span>{t.emColState}</span><span>{t.emColWeight}</span><span>{t.emColReliability}</span></div>{data.engines.map(e=><div className="engine-row" key={e.name}><strong>{e.name}</strong><b>{e.score.toFixed(1)}</b><span>{e.state}</span><div className="weight"><i style={{width:`${Math.max(0,Math.min(100,e.weight*100))}%`}}/><small>{e.weight.toFixed(3)}</small></div><span>{e.reliability}</span></div>)}</div></section><div className="dashboard-split"><section className="panel"><span className="eyebrow">{t.emLearningState}</span><h2>{t.emAdaptiveWeighting}</h2><p className="terminal-copy">{t.emAdaptiveCopy}</p><div className="confidence-block"><span>{t.emRuntime}</span><strong>{error?t.statusDegraded:t.ccActive}</strong></div></section><section className="panel"><span className="eyebrow">{t.emDecisionQuality}</span><h2>{data.symbol} {t.emEvidence}</h2><div className="decision-stats"><div><span>{t.colConfidence}</span><b>{data.confidence.toFixed(1)}%</b></div><div><span>{t.ccQualityLabel}</span><b>{data.quality.toFixed(1)}%</b></div><div><span>{t.colRisk}</span><b>{data.risk.toFixed(1)}%</b></div></div></section></div></div>
}
function State({t,text,detail,retry}:{t:Copy;text:string;detail?:string;retry?:()=>void}){return <div className="page"><section className="panel empty-state"><h2>{text}</h2>{detail&&<p>{detail}</p>}{retry&&<button onClick={retry}>{t.retryConnection}</button>}</section></div>}
