[package]
name = "product-api"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
shared = { path = "../shared" }
score-engine = { path = "../score-engine" }
axum = { version = "0.7", features = ["macros"] }
axum-extra = { version = "0.9", features = ["cookie"] }
redis = { version = "0.27", features = ["tokio-comp", "tokio-native-tls-comp"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "migrate", "time", "json"] }
tower-http = { version = "0.6", features = ["cors", "trace", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
argon2 = "0.5"
rand = "0.8"
sha2 = "0.10"
time = { version = "0.3", features = ["formatting", "parsing"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
futures-util = "0.3"
