import { createContext, useContext, useMemo, useState, type ReactNode } from 'react';
export type Lang='tr'|'en'|'de'|'fr'|'ar'|'ru';
const copy={
tr:{login:'Giriş yap',register:'Kayıt ol',email:'E-posta',password:'Şifre',firstName:'Ad',lastName:'Soyad',welcome:'Piyasayı izleme. Piyasanın izini sür.',subtitle:'Kurumsal düzey piyasa istihbaratı',switchRegister:'Hesabın yok mu?',switchLogin:'Zaten hesabın var mı?',footer:'BOLDTRACE Market Intelligence',disclaimer:'Yatırım tavsiyesi değildir.',rememberMe:'Bu cihazı hatırla',termsCheckbox:'Kullanım Koşulları\'nı kabul ediyorum ve bunun yatırım tavsiyesi olmayan istatistiksel bilgi olduğunu anlıyorum.',authorizing:'DOĞRULANIYOR…',errorInvalidInput:'Lütfen tüm alanları geçerli şekilde doldurun.',errorTermsRequired:'Devam etmek için Kullanım Koşulları\'nı kabul etmelisiniz.',errorEmailTaken:'Bu e-posta zaten kayıtlı.',errorInvalidCredentials:'E-posta veya şifre hatalı.',errorServiceUnavailable:'Hizmet şu anda kullanılamıyor, lütfen tekrar deneyin.',errorGeneric:'Bir şeyler ters gitti, lütfen tekrar deneyin.'},
en:{login:'Sign in',register:'Create account',email:'Email',password:'Password',firstName:'First name',lastName:'Last name',welcome:'Do not watch the market. Trace it.',subtitle:'Institutional-grade market intelligence',switchRegister:'New to BOLDTRACE?',switchLogin:'Already have an account?',footer:'BOLDTRACE Market Intelligence',disclaimer:'Not investment advice.',rememberMe:'Remember this device',termsCheckbox:'I agree to the Terms of Service and understand this is statistical information, not investment advice.',authorizing:'AUTHORIZING…',errorInvalidInput:'Please fill in all fields with valid values.',errorTermsRequired:'You must accept the Terms of Service to continue.',errorEmailTaken:'That email is already registered.',errorInvalidCredentials:'Incorrect email or password.',errorServiceUnavailable:'Service is temporarily unavailable, please try again.',errorGeneric:'Something went wrong, please try again.'},
de:{login:'Anmelden',register:'Konto erstellen',email:'E-Mail',password:'Passwort',firstName:'Vorname',lastName:'Nachname',welcome:'Beobachte den Markt nicht. Verfolge seine Spur.',subtitle:'Marktintelligenz auf institutionellem Niveau',switchRegister:'Neu bei BOLDTRACE?',switchLogin:'Bereits registriert?',footer:'BOLDTRACE Market Intelligence',disclaimer:'Keine Anlageberatung.',rememberMe:'Dieses Gerät merken',termsCheckbox:'Ich stimme den Nutzungsbedingungen zu und verstehe, dass dies statistische Informationen und keine Anlageberatung sind.',authorizing:'AUTORISIERUNG…',errorInvalidInput:'Bitte füllen Sie alle Felder gültig aus.',errorTermsRequired:'Sie müssen den Nutzungsbedingungen zustimmen, um fortzufahren.',errorEmailTaken:'Diese E-Mail ist bereits registriert.',errorInvalidCredentials:'E-Mail oder Passwort ist falsch.',errorServiceUnavailable:'Dienst vorübergehend nicht verfügbar, bitte erneut versuchen.',errorGeneric:'Etwas ist schiefgelaufen, bitte erneut versuchen.'},
fr:{login:'Se connecter',register:'Créer un compte',email:'E-mail',password:'Mot de passe',firstName:'Prénom',lastName:'Nom',welcome:'Ne regardez pas le marché. Suivez sa trace.',subtitle:'Intelligence de marché de niveau institutionnel',switchRegister:'Nouveau sur BOLDTRACE ?',switchLogin:'Déjà un compte ?',footer:'BOLDTRACE Market Intelligence',disclaimer:"Ceci ne constitue pas un conseil en investissement.",rememberMe:'Se souvenir de cet appareil',termsCheckbox:"J'accepte les Conditions d'utilisation et je comprends qu'il s'agit d'informations statistiques, non d'un conseil en investissement.",authorizing:'AUTORISATION…',errorInvalidInput:'Veuillez remplir correctement tous les champs.',errorTermsRequired:"Vous devez accepter les Conditions d'utilisation pour continuer.",errorEmailTaken:'Cet e-mail est déjà enregistré.',errorInvalidCredentials:'E-mail ou mot de passe incorrect.',errorServiceUnavailable:'Service temporairement indisponible, veuillez réessayer.',errorGeneric:"Une erreur s'est produite, veuillez réessayer."},
ar:{login:'تسجيل الدخول',register:'إنشاء حساب',email:'البريد الإلكتروني',password:'كلمة المرور',firstName:'الاسم الأول',lastName:'اسم العائلة',welcome:'لا تراقب السوق. تتبّع أثره.',subtitle:'استخبارات سوق بمستوى مؤسسي',switchRegister:'جديد في BOLDTRACE؟',switchLogin:'لديك حساب بالفعل؟',footer:'BOLDTRACE Market Intelligence',disclaimer:'ليست نصيحة استثمارية.',rememberMe:'تذكر هذا الجهاز',termsCheckbox:'أوافق على شروط الخدمة وأفهم أن هذه معلومات إحصائية وليست نصيحة استثمارية.',authorizing:'جارٍ التحقق…',errorInvalidInput:'يرجى ملء جميع الحقول بقيم صحيحة.',errorTermsRequired:'يجب الموافقة على شروط الخدمة للمتابعة.',errorEmailTaken:'هذا البريد الإلكتروني مسجل بالفعل.',errorInvalidCredentials:'البريد الإلكتروني أو كلمة المرور غير صحيحة.',errorServiceUnavailable:'الخدمة غير متاحة مؤقتًا، يرجى المحاولة مرة أخرى.',errorGeneric:'حدث خطأ ما، يرجى المحاولة مرة أخرى.'},
ru:{login:'Войти',register:'Создать аккаунт',email:'Эл. почта',password:'Пароль',firstName:'Имя',lastName:'Фамилия',welcome:'Не наблюдай за рынком. Отслеживай его след.',subtitle:'Рыночная аналитика институционального уровня',switchRegister:'Впервые в BOLDTRACE?',switchLogin:'Уже есть аккаунт?',footer:'BOLDTRACE Market Intelligence',disclaimer:'Не является инвестиционной рекомендацией.',rememberMe:'Запомнить это устройство',termsCheckbox:'Я принимаю Условия использования и понимаю, что это статистическая информация, а не инвестиционный совет.',authorizing:'ПРОВЕРКА…',errorInvalidInput:'Пожалуйста, заполните все поля корректно.',errorTermsRequired:'Чтобы продолжить, необходимо принять Условия использования.',errorEmailTaken:'Этот адрес электронной почты уже зарегистрирован.',errorInvalidCredentials:'Неверный адрес электронной почты или пароль.',errorServiceUnavailable:'Сервис временно недоступен, попробуйте снова.',errorGeneric:'Что-то пошло не так, попробуйте снова.'}}
export type Copy=typeof copy.en;
const C=createContext<{lang:Lang;t:Copy;setLang:(x:Lang)=>void}>({lang:'en',t:copy.en,setLang:()=>{}});
export function I18nProvider({children}:{children:ReactNode}){const [lang,setLang]=useState<Lang>(()=>(localStorage.getItem('boldtrace.lang') as Lang)||'en');const value=useMemo(()=>{localStorage.setItem('boldtrace.lang',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';return{lang,t:copy[lang],setLang}},[lang]);return <C.Provider value={value}>{children}</C.Provider>}
export const useI18n=()=>useContext(C);
